### ISSUE TITLE
Google Cal: parse for e-conomic number

### ISSUE THREAD

**Issue by pgn** [pawel-lewtak/economic-py#10]
Try to parse Google Calendar event description for economic number and use while registering time.

Example Description

Panowie,

Spotkajmy się na dalsze zagajenie tematu.

E-conomic: 252

Do zobaczenia,
Marek

**Comment by pawel-lewtak** [comment]
It's already planned improvement but wasn't added as a task till now.

**Comment by pawel-lewtak** [comment]
Closing as a duplicate of issue #3 - development will continue there.
