### ISSUE TITLE
Possibility to set entry date as a parameter

### ISSUE THREAD

**Issue by sadek123** [pawel-lewtak/economic-py#8]
Currently the scripts adds all entries from Jira/Calendera for current day.
I would like to have possibility to add entries for previous days, etc.

./run.py --date=2014-04-01

**Comment by pawel-lewtak** [comment]
`--date` parameter was added to export events from given day. Date should be using format YYYY-MM-DD

Sadly, JIRA isn't supported yet with this feature.

**Comment by pawel-lewtak** [comment]
Unless Atlassian offers some kind of API to get user's tasks for given day in the past I'm not planning to support JIRA with this parameter. Feel free to implement it though if you'd like.
